website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    firstName = db.Column(db.String(150))
    lastName = db.Column(db.String(150))
    bmi = db.relationship('Bmi')
    entries = db.relationship('Entries')

class Bmi(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    age = db.Column(db.Integer)
    weight = db.Column(db.Integer)
    height = db.Column(db.Integer)
    whh = db.Column(db.Integer)
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

class Entries(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'FragrancE18##'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Bmi, Entries
    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))
    return app

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.entries'))
            else:
                flash('Incorrect password. Try again', category='error')
        else:
            flash('Email address does not exist. Sign up', category='error')
    return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        firstName = request.form.get('firstName')
        lastName = request.form.get('lastName')
        email = request.form.get('email')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email address already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters', category='error')
        elif len(firstName) < 2:
            flash('First name must be greater than 1 character', category='error')
        elif len(lastName) < 2:
            flash('Last name must be greater than 1 character', category='error')
        elif len(password1) < 7 and len(password1) > 20:
            flash('Password must 8 to 20 characters', category='error')
        elif password1 != password2:
            flash('Passwords do not match', category='error')
        else:
            new_user = User(email=email, firstName=firstName, lastName=lastName, password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            flash('Account created successfully!', category='success')
            return redirect(url_for('views.entries'))
            
    return render_template("signup.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, request, flash, jsonify
from flask_login import login_required, current_user
from . import db
from .models import Entries, Bmi
import json


views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
def home():
    return render_template('home.html', user=current_user)

@views.route('/info', methods=['GET', 'POST'])
def info():
    return render_template('info.html', user=current_user)

@views.route('/about_us', methods=['GET', 'POST'])
def about_us():
    return render_template('aboutus.html', user=current_user)


@views.route('/calculate', methods=['GET', 'POST'])
@login_required
def calculate():
    whh=''
    if request.method == 'POST':
        age = request.form.get('age')
        height = float(request.form.get('height'))
        weight = float(request.form.get('weight'))
        whh = round(weight / ((height / 100) ** 2), 2)

        if weight == 0:
            flash('Weight is too low', category='error')
        else:
            new_bmi = Bmi(age=age, height=height, weight=weight, whh=whh, user_id=current_user.id)
            db.session.add(new_bmi)
            db.session.commit()
            flash('BMI calculated', category='success')
    return render_template("calculate.html", whh=whh, user=current_user)

@views.route('/entries', methods=['GET', 'POST'])
@login_required
def entries():
    if request.method == 'POST':
        entry = request.form.get('entry')

        if len(entry) < 1:
            flash('Journal entry is too short!', category='error')
        else:
            new_entry = Entries(data=entry, user_id=current_user.id)
            db.session.add(new_entry)
            db.session.commit()
            flash('Journal entry added!', category='success')
    return render_template("entries.html", user=current_user)

@views.route('/delete-entry', methods=['POST'])
def delete_entry():
    entry = json.loads(request.data)
    entryId = entry['entryId']
    entry = Entries.query.get(entryId)
    if entry:
        if entry.user_id == current_user.id:
            db.session.delete(entry)
            db.session.commit()
    return jsonify({})

website/templates/aboutus.html
{% extends "base2.html" %}
{% block title %}About Us{% endblock %}

{% block content %}

<div class="content">
<h1 align="center">About Us</h1>
<p align="center">We are a team of individuals passionate about helping people live long vibrant healthy lives.</p><br>
<p align="center">Passionate about helping people develop a good, long and viable relationship with food.</p>
<p align="center"><b>And that is all that matters, because you matter.</b></p>
<p align="center">This is a simple ALX end of Foundations Project.</p>
<p align="center">You can get the source code at <a href="https://github.com/TabbieManywanda/portfolio-project">my github</a> </p>
</div>

{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width", initial-scale="1">
        <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          crossorigin="anonymous">
        <link
          rel="stylesheet"
          href="{{ url_for('static', filename='style.css') }}">
        <title>{% block title %}Mealix - Meals made easier{% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{{ url_for('views.home') }}">
              <img src="{{ url_for('static', filename='favicon.ico')}}" width="30" height="30" class="d-inline-block align-top" alt="">
              Mealix
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                <div class="navbar-nav">
                  {% if user.is_authenticated %}
                    <a class="nav-item nav-link" id="entries" href="/entries">My Entries</a>
                    <a class="nav-item nav-link" id="calculate" href="/calculate">Get my BMI</a>
                    <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                  {% else %}
                    <a class="nav-item nav-link" id="login" href="/login">Login</a>
                    <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
                  {% endif %}
                </div>
            </div>
        </nav>

        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
          {% if category == 'error' %}
          <div class="alert alert-danger alter-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% else %}
          <div class="alert alert-success alter-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endif %}
          {% endfor %}
        {% endif %}
        {% endwith %}

        <div class="container">
          {% block content %}
          {% endblock %}
        </div>

        <script
          src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
          integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
          crossorigin="anonymous"></script>
        <script
          src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
          integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
          crossorigin="anonymous"></script>
        <script
          src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
          integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
          crossorigin="anonymous"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='index.js') }}"></script>
    </body>
</html>

website/templates/base2.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width", initial-scale="1">
        <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          crossorigin="anonymous">
        <link
          rel="stylesheet"
          href="{{ url_for('static', filename='style1.css') }}">
        
        <title>{% block title %}Mealix - Meals made easier{% endblock %}</title>
    </head>
    <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for('views.home') }}">
          <img src="{{ url_for('static', filename='favicon.ico')}}" width="30" height="30" class="d-inline-block align-top" alt="">
          Mealix
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
                <a class="nav-item nav-link" id="info" href="/info">How It Works</a>
                <a class="nav-item nav-link" id="about_us" href="/about_us">About Us</a>
                <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a> 
            </div>
        </div>
      </nav>

      <div class="container">
        {% block content %}
        {% endblock %}
      </div>

      <script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
      <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
      <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    </body>
</html>

website/templates/calculate.html
{% extends "base.html" %}
{% block title %}Get my BMI{% endblock %}

{% block content %}

<div align="center">
<div class="container">
    <div class="box">
        <h1>BMI Calculator</h1>
        <form method="POST">
            <div class="content">
                <div class="input">
                    <label for="age">Age</label>
                    <input type="text" class="text-input" id="age" autocomplete="off" required>
                </div>
                <div class="containerHW">
                    <div class="inputH">
                        <label for="height">Height(cm)</label>
                        <input type="text" name="height" id="height" required>
                    </div>
                    <div class="inputW">
                        <label for="weight">Weight(kg)</label>
                        <input type="text" name="weight" id="weight" required>
                    </div>
                </div>
                <button type="submit" id="bmi" class="btn btn-primary">Get my BMI!</button>
            </div>
        </form>
        <div class="result">
            <p>Your BMI is:</p>
            {% if whh %}
            <div id="result">{{ whh }}</div>
            {% endif %}
            <p class="comment"></p>
        </div>
    </div>
    <div id="my_modal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <p id="modal-text"></p>
        </div>
    </div>
</div>
</div>

{% endblock %}

website/templates/entries.html
{% extends "base.html" %}
{% block title %}My Entries{% endblock %}

{% block content %}

<h1 align="center">My Food Journal</h1>
<h3 align="center">#ProgressReport</h3>
<br>
<form method="POST">
    <textarea name="entry" id="entry" class="form-control" placeholder="What foods did I eat today?"></textarea>
    <br>
    <div align="center">
        <button type="submit" class="btn btn-primary">Make Entry</button>
    </div>
</form>
<br>
<ul class="list-group list-group-flush" id="entries">
    {% for entry in user.entries %}
    <li class="list-group-item">
        <small id="passwordHelpInline" class="text-muted">{{ entry.date }}</small>
        <hr>
        {{ entry.data }}
        <button type="button" class="close" onClick="deleteNote({{ entry.id }})">
            <span aria-hidden="true">&times;</span>
        </button>
    </li>
    {% endfor %}
</ul>

{% endblock %}

website/templates/home.html
{% extends "base2.html" %}
{% block title %}Home{% endblock %}

{% block content %}
  
<div class="content">
  <h1 align="center">WELCOME TO MEALIX</h1>
  <h3 align="center">The first step to the rest of your life</h3>
  <h5 align="center">Let's take a journey of imagination for a bit...</h5>
  <p align="center">Imagine a world where making one change in your habits could double your health progress.</p>
  <p align="center">A habit that takes less than 10 minutes out of your daily 1440 minutes.</p>
  <p align="center">It may sound too good to be true but...(here is where it gets juicy)</p>
  <p align="center">Several studies have shown that people who keep food journals are more likely to be successful in achieving weight goals and maintaining in the long run.</p>
  <p align="center">In fact, people keeping a food journal 6 days a week lost about twice as much weight as those who kept food records one day a week or less.</p>
  <p align="center">And we are here to give that gift to you. So how about we get started already...</p>
</div>

{% endblock %}

website/templates/info.html
{% extends "base2.html" %}
{% block title %}How it works{% endblock %}

{% block content %}

<div class="content">
<h1 align="center">How To Journal With Us</h1>

<div>
    <div>
        <p align="center">Step 1: Sign Up</p><br>
    </div>
    <div>
        <p align="center">Step 2: Calculate your BMI</p><br>
    </div>
    <div>
        <p align="center">Step 3: Note down your daily food intake</p><br>
    </div>
</div>

<p align="center"><b>It is just that easy. Sign Up or Login if you have an account.</b></p>
</div>
<p align="center"><b>It is just that easy. Sign Up or Login if you have an account.</b></p>
</div>

{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block content %}

<form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">  
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter password">
    </div>
    <p>
        Have no account? <a href="{{ url_for('auth.sign_up') }}">Sign up here</a>.
    </p>
    <br>
    <button type="submit" class="btn btn-primary">Login</button>
</form>

{% endblock %}

website/templates/signup.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock %}

{% block content %}

<form method="POST">
    <h3 align="center">Sign Up</h3>
    <div class="form-group">
        <label for="firstName">First Name</label>
        <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Enter first name">  
    </div>
    <div class="form-group">
        <label for="lastName">Last Name</label>
        <input type="text" class="form-control" id="lastName" name="lastName" placeholder="Enter last name"> 
    </div>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">  
    </div>
    <div class="form-group">
        <label for="password1">Password</label>
        <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter password" aria-describedby="passwordHelpInline">
        <small id="passwordHelpInline" class="text-muted">
            Must be 8-20 characters long.
        </small>
    </div>
    <div class="form-group">
        <label for="password2">Password</label>
        <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm password">
    </div>
    <p>
        Already have an account? <a href="{{ url_for('auth.login') }}">Login here</a>.
    </p>
    <br>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}